NEI <- readRDS("../DataAnalysis/summarySCC_PM25.rds")
SCC <- readRDS("../DataAnalysis/Source_Classification_Code.rds")
data <- tapply(NEI$Emissions, NEI$year, sum)
par(mfrow = c(1,1), mar = c(4,4,2,1))
plot(names(data), data, xlab = "Year", ylab = "PM2.5 Emissions", xlim = c(1998,2008), ylim = range(data), type = "p",main = "Total PM2.5 emissions accross the years", pch = 19, col = "orangered")
lines(names(data), data, lty = 1, lwd = 2, col = "red")
dev.copy(png, filename = "plot1.png")
dev.off()
