library(ggplot2)
NEI <- readRDS("../DataAnalysis/summarySCC_PM25.rds")
SCC <- readRDS("../DataAnalysis/Source_Classification_Code.rds")
data <- subset(NEI, NEI$fips == "24510") #& (NEI$year == 1999 | NEI$year == 2008))
data <- aggregate(Emissions ~ year + type, data = data, sum)
dataPlot <- ggplot(data, aes(year, Emissions, color = type))
dataPlot <- dataPlot + geom_line() + xlab("YEAR") + ylab("PM 2.5 Emissions") + ggtitle("Emissions from Baltimore City based on type")
print(dataPlot)
dev.copy(png, filename = "plot3.PNG")
dev.off()
