NEI <- readRDS("../DataAnalysis/summarySCC_PM25.rds")
SCC <- readRDS("../DataAnalysis/Source_Classification_Code.rds")
data <- subset(NEI, NEI$fips == "24510")
vehicle <- grepl("vehicle", SCC$SCC.Level.Two, ignore.case = TRUE)
subSCC <- SCC[vehicle,]
data <- merge(data , subSCC, by = "SCC")
data <- tapply(data$Emissions, data$year, sum)
plot(names(data), data, xlab = "Year", ylab = "PM2.5 Emissions", xlim = c(1998,2008), type = "p",main = "Total PM2.5 emissions from Motor Vehicle Sources", pch = 19, col = "orangered")
lines(names(data), data, lty = 1, lwd = 2, col = "red")
dev.copy(png, filename = "plot5.png")
dev.off()
